---
- name: Create backup directory
  local_action:
    module: file
    path: "backup/junos_config.{{ datetime }}"
    state: directory 

- name: Create snapshot
  connection: network_cli
  cli_command:
    command: show configuration | no-more
  register: output

- name: Save snapshot as a latest configuration backup
  local_action: 
    module: copy 
    content: "{{ output.stdout }}"
    dest: "backup/junos_config.{{ datetime }}/{{ hostname }}.cfg"

